#Build and push Docker Images to Google Artifact Registry
on:
  release:
    types:
      - published

name: Build and push Docker images to Google Artifact Registry

jobs:
  image-to-google-artifact-registry:
    timeout-minutes: 10
    runs-on: linux
    env:
      NAMESPACE: docker
      IMAGE: my-app
      CONTAINER_NAME: my-app-${{ github.sha }}
    steps:
      - name: Prep cleanup test container
        run: |
          if [ "$(docker ps -a -q --filter ancestor=image-test)" ]; then
              docker rm $(docker stop $(docker ps -a -q --filter ancestor=image-test --format="{{.ID}}"))
          fi

      - name: Change permissions
        run: |
          sudo chmod 777 -R /home/runner/actions-runner/_work/my-app/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          docker build -f Dockerfile-local . -t image-test
          docker run -d --name=$CONTAINER_NAME image-test

      - name: Build
        run: |
          docker exec -t $CONTAINER_NAME npm run build
          docker cp $CONTAINER_NAME:/usr/src/app/build ./build

      - name: Post cleanup test container
        run: |
          if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
            docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME
          fi

      - name: Build image
        run: docker build . -t $IMAGE

      - name: Tag image
        run: docker image tag $IMAGE europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$NAMESPACE/$IMAGE:${GITHUB_REF#refs/tags/}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_GAR_SA_KEY }}
          export_default_credentials: true

      - name: Push image to google registry
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet && docker push europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$NAMESPACE/$IMAGE:${GITHUB_REF#refs/tags/}

      - name: clean
        uses: docker://centos
        if: ${{ always() }}
        continue-on-error: true
        with:
          args: '/bin/rm /github/workspace -rf'
