FROM node:16-bullseye-slim

# Change timezone to Paris
RUN rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime

RUN apt-get update && apt-get install -y \
  git \
  libgtk2.0-0 \
  libgtk-3-0 \
  libnotify-dev \
  libgconf-2-4 \ 
  libnss3 \
  libxss1 \
  libasound2 \
  libxtst6 \
  libgbm-dev \
  xauth \
  xvfb && apt-get purge --auto-remove -y

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY . /usr/src/app

RUN npm ci

EXPOSE 3000

CMD ["npm", "start"]
